### ISSUE TITLE
Internal Polaris Team Swag

### ISSUE THREAD

**Issue by jamesbull** [Shopify/foundational-design-system-proto#194]
As an action item from the Homesite in July, we're going to produce some swag for the Polaris team.

- [Project plan](https://docs.google.com/document/d/1h9ougkERf4GbyYtH7pKtP6DRZNW0f5Xwpg3GUOcJWwE/edit#)

**Comment by alex-page** [comment]
@jamesbull @erncat any updates here?

**Comment by erncat** [comment]
Finalizing the artwork this week!

Next steps are picking the way we are printing & getting everyone's info. I plan on working on the logistics of it all this week!

**Comment by alex-page** [comment]
Thank you @erncat
